id: ferryman
start: village-road
metadata:
  title: Ferryman
  version: 0.1.11
  copyright: |-
    Ferryman: Journey of a Lost Soul
    Copyright (c) 2026 Sgail Ltd, released under the MIT licence for the purposes of providing a demo of the Stage engine.

store:
  rating: PEGI 16
  genres:
    - Horror
    - Fantasy
  release:
    date: "2026-01-01"
  developer:
    name: Sgail Games
    website: https://sgail.com
  publisher:
    name: Sgail Games
    website: https://sgail.com
  website: https://engine.sgail.com
  description: |-
    Ferryman, a game about a lost soul's journey.
  assets:
    tile: assets/icon.png
    banner: assets/cover.png

export:
  bundle-id: com.sgail.ferryman
  platforms:
    macos: [arm64, x86_64]
    linux: [x86_64, arm64]
    windows: [x86_64]
